# Importing libraries and packages
We first import all the libraries and packages we'll need for this assignment

In [106]:
#!pip install numpy pandas tensorflow keras sklearn tqdm matplotlib

import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Importing the data set
Getting the data from the net

In [107]:
# putting the data in a Pandas DataFrame
data_df = pd.read_csv('http://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
data_df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

# A. Build a baseline model
## Data Wrangling

In [108]:
# checking if data contains null values
data_df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [109]:
# we remove the Strength column from the data and store it in y as targets
y = data_df.pop('Strength')
y.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [110]:
# the remaining data is X, the predictors used to train the model
X = data_df
X.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [111]:
# we check the sets have the same number of rows
print(X.shape, y.shape)

(1030, 8) (1030,)

## Create and evaluate model
Randomly split the data into a training and test sets by holding 30% of the data for testing. You can use the train_test_splithelper function from Scikit-learn.

In [112]:
# we split the predictors (X) and targets (y) in train and test sets with 30% of the data for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

#checking the size of training and testing sets for both X and y
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(721, 8) (309, 8) (721,) (309,)

Train the model on the training data using 50 epochs.

Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. You can use the mean_squared_error function from Scikit-learn.

Repeat steps 1 - 3, 50 times, i.e., create a list of 50 mean squared errors.

Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. You can use the mean_squared_error function from Scikit-learn.

In [141]:
# creating a neural network with 1 hidden layer of 10 nodes, and a ReLU activation function
# using the adam optimizer and the mean squared error as the loss function
def create_model_1():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(X_train.shape[1],))) # input shape is the number of columns of X_train
    model.add(Dense(1))

    # compiling the model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# creating a list to hold all mean squared errors
mse_list_model_a = []

# training the model 50 times and getting the mse for each iteration, storing the values in the list
for i in range(50):
    # creating the model
    print(f"Model A epoch {i+1} of 50")
    model_a = create_model_1()
    
    #fitting the model
    model_a.fit(X_train, y_train, validation_split=0.3, epochs=50, verbose=0, batch_size=64)
    
    # using the model to predict values
    y_hat_a = model_a.predict(X_test)
    
    # append mse between predicted data and actual data
    mse_list_model_a.append(mean_squared_error(y_test, y_hat_a))

Model A epoch 1 of 50
10/10 [==============================] - 0s 677us/step
Model A epoch 2 of 50
10/10 [==============================] - 0s 781us/step
Model A epoch 3 of 50
10/10 [==============================] - 0s 698us/step
Model A epoch 4 of 50
10/10 [==============================] - 0s 680us/step
Model A epoch 5 of 50
10/10 [==============================] - 0s 679us/step
Model A epoch 6 of 50
10/10 [==============================] - 0s 647us/step
Model A epoch 7 of 50
10/10 [==============================] - 0s 951us/step
Model A epoch 8 of 50
10/10 [==============================] - 0s 746us/step
Model A epoch 9 of 50
10/10 [==============================] - 0s 838us/step
Model A epoch 10 of 50
10/10 [==============================] - 0s 748us/step
Model A epoch 11 of 50
10/10 [==============================] - 0s 796us/step
Model A epoch 12 of 50
10/10 [==============================] - 0s 750us/step
Model A epoch 13 of 50
10/10 [==============================] - 0s 791us/step
Model A epoch 14 of 50
10/10 [==============================] - 0s 658us/step
Model A epoch 15 of 50
10/10 [==============================] - 0s 855us/step
Model A epoch 16 of 50
10/10 [==============================] - 0s 675us/step
Model A epoch 17 of 50
10/10 [==============================] - 0s 752us/step
Model A epoch 18 of 50
10/10 [==============================] - 0s 764us/step
Model A epoch 19 of 50
10/10 [==============================] - 0s 813us/step
Model A epoch 20 of 50
10/10 [==============================] - 0s 757us/step
Model A epoch 21 of 50
10/10 [==============================] - 0s 886us/step
Model A epoch 22 of 50
10/10 [==============================] - 0s 656us/step
Model A epoch 23 of 50
10/10 [==============================] - 0s 746us/step
Model A epoch 24 of 50
10/10 [==============================] - 0s 830us/step
Model A epoch 25 of 50
10/10 [==============================] - 0s 668us/step
Model A epoch 26 of 50
10/10 [==============================] - 0s 687us/step
Model A epoch 27 of 50
10/10 [==============================] - 0s 744us/step
Model A epoch 28 of 50
10/10 [==============================] - 0s 722us/step
Model A epoch 29 of 50
10/10 [==============================] - 0s 685us/step
Model A epoch 30 of 50
10/10 [==============================] - 0s 767us/step
Model A epoch 31 of 50
10/10 [==============================] - 0s 724us/step
Model A epoch 32 of 50
10/10 [==============================] - 0s 793us/step
Model A epoch 33 of 50
10/10 [==============================] - 0s 787us/step
Model A epoch 34 of 50
10/10 [==============================] - 0s 677us/step
Model A epoch 35 of 50
10/10 [==============================] - 0s 664us/step
Model A epoch 36 of 50
10/10 [==============================] - 0s 740us/step
Model A epoch 37 of 50
10/10 [==============================] - 0s 774us/step
Model A epoch 38 of 50
10/10 [==============================] - 0s 1ms/step
Model A epoch 39 of 50
10/10 [==============================] - 0s 744us/step
Model A epoch 40 of 50
10/10 [==============================] - 0s 827us/step
Model A epoch 41 of 50
10/10 [==============================] - 0s 746us/step
Model A epoch 42 of 50
10/10 [==============================] - 0s 731us/step
Model A epoch 43 of 50
10/10 [==============================] - 0s 680us/step
Model A epoch 44 of 50
10/10 [==============================] - 0s 723us/step
Model A epoch 45 of 50
10/10 [==============================] - 0s 664us/step
Model A epoch 46 of 50
10/10 [==============================] - 0s 1ms/step
Model A epoch 47 of 50
10/10 [==============================] - 0s 662us/step
Model A epoch 48 of 50
10/10 [==============================] - 0s 778us/step
Model A epoch 49 of 50
10/10 [==============================] - 0s 705us/step
Model A epoch 50 of 50
10/10 [==============================] - 0s 714us/step

## Compute MSE
Report the mean and the standard deviation of the mean squared errors

In [176]:
def get_mean_and_std_from_mse_list(name, mse_list):
    return pd.DataFrame({"Model":name, "Mean": np.asarray(mse_list).mean(), "St. Dev.": np.asarray(mse_list).std()}, index=[0])

results = get_mean_and_std_from_mse_list('A', mse_list_model_a)
results

  Model        Mean     St. Dev.
0     A  1374.30739  2147.179694

# B. Normalize the data
Repeat Part A but use a normalized version of the data. Recall that one way to normalize the data is by subtracting the mean from the individual predictors and dividing by the standard deviation.

In [143]:
# we normalize the predictors
X_norm = (X_train - X_train.mean()) / X_train.std()
X_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
196,-0.827909,-0.854703,0.761173,-0.765956,0.227116,0.415257,1.675640,-0.292777
631,0.374563,-0.854703,-0.816346,0.103676,-1.013292,1.136190,0.141805,-0.633406
81,0.317346,1.567846,-0.816346,-1.233856,1.351752,-1.550115,1.357391,-0.698287
526,0.688331,-0.638098,1.396890,-1.314203,0.789434,-0.405028,0.366451,-0.698287
830,-1.129680,1.311341,1.506767,-0.132637,2.129073,-1.729712,-0.382369,-0.292777

In [144]:
#we normalize the test data as well
X_norm_test = (X_test - X_test.mean()) / X_test.std()

# same as part A, but with the normalized data
# creating a list to hold all mean squared errors
mse_list_model_b = []

# training the model 50 times and getting the mse for each iteration, storing the values in the list
for i in range(50):
    # creating the model
    print(f"Model B epoch {i+1} of 50")
    model_b = create_model_1()
    
    #fitting the model with the normalized data
    model_b.fit(X_norm, y_train, validation_split=0.3, epochs=50, verbose=0, batch_size=64)
    
    # using the model to predict values
    y_hat_b = model_b.predict(X_norm_test)
    
    # append mse between predicted data and actual data
    mse_list_model_b.append(mean_squared_error(y_test, y_hat_b))

Model B epoch 1 of 50
10/10 [==============================] - 0s 729us/step
Model B epoch 2 of 50
10/10 [==============================] - 0s 654us/step
Model B epoch 3 of 50
10/10 [==============================] - 0s 1ms/step
Model B epoch 4 of 50
10/10 [==============================] - 0s 725us/step
Model B epoch 5 of 50
10/10 [==============================] - 0s 711us/step
Model B epoch 6 of 50
10/10 [==============================] - 0s 787us/step
Model B epoch 7 of 50
10/10 [==============================] - 0s 725us/step
Model B epoch 8 of 50
10/10 [==============================] - 0s 675us/step
Model B epoch 9 of 50
10/10 [==============================] - 0s 696us/step
Model B epoch 10 of 50
10/10 [==============================] - 0s 669us/step
Model B epoch 11 of 50
10/10 [==============================] - 0s 692us/step
Model B epoch 12 of 50
10/10 [==============================] - 0s 642us/step
Model B epoch 13 of 50
10/10 [==============================] - 0s 881us/step
Model B epoch 14 of 50
10/10 [==============================] - 0s 675us/step
Model B epoch 15 of 50
10/10 [==============================] - 0s 704us/step
Model B epoch 16 of 50
10/10 [==============================] - 0s 723us/step
Model B epoch 17 of 50
10/10 [==============================] - 0s 674us/step
Model B epoch 18 of 50
10/10 [==============================] - 0s 723us/step
Model B epoch 19 of 50
10/10 [==============================] - 0s 808us/step
Model B epoch 20 of 50
10/10 [==============================] - 0s 1ms/step
Model B epoch 21 of 50
10/10 [==============================] - 0s 718us/step
Model B epoch 22 of 50
10/10 [==============================] - 0s 725us/step
Model B epoch 23 of 50
10/10 [==============================] - 0s 807us/step
Model B epoch 24 of 50
10/10 [==============================] - 0s 776us/step
Model B epoch 25 of 50
10/10 [==============================] - 0s 818us/step
Model B epoch 26 of 50
10/10 [==============================] - 0s 797us/step
Model B epoch 27 of 50
10/10 [==============================] - 0s 714us/step
Model B epoch 28 of 50
10/10 [==============================] - 0s 856us/step
Model B epoch 29 of 50
10/10 [==============================] - 0s 821us/step
Model B epoch 30 of 50
10/10 [==============================] - 0s 801us/step
Model B epoch 31 of 50
10/10 [==============================] - 0s 659us/step
Model B epoch 32 of 50
10/10 [==============================] - 0s 732us/step
Model B epoch 33 of 50
10/10 [==============================] - 0s 1ms/step
Model B epoch 34 of 50
10/10 [==============================] - 0s 817us/step
Model B epoch 35 of 50
10/10 [==============================] - 0s 765us/step
Model B epoch 36 of 50
10/10 [==============================] - 0s 770us/step
Model B epoch 37 of 50
10/10 [==============================] - 0s 795us/step
Model B epoch 38 of 50
10/10 [==============================] - 0s 655us/step
Model B epoch 39 of 50
10/10 [==============================] - 0s 725us/step
Model B epoch 40 of 50
10/10 [==============================] - 0s 724us/step
Model B epoch 41 of 50
10/10 [==============================] - 0s 808us/step
Model B epoch 42 of 50
10/10 [==============================] - 0s 889us/step
Model B epoch 43 of 50
10/10 [==============================] - 0s 722us/step
Model B epoch 44 of 50
10/10 [==============================] - 0s 678us/step
Model B epoch 45 of 50
10/10 [==============================] - 0s 758us/step
Model B epoch 46 of 50
10/10 [==============================] - 0s 675us/step
Model B epoch 47 of 50
10/10 [==============================] - 0s 801us/step
Model B epoch 48 of 50
10/10 [==============================] - 0s 755us/step
Model B epoch 49 of 50
10/10 [==============================] - 0s 833us/step
Model B epoch 50 of 50
10/10 [==============================] - 0s 661us/step

## Compute MSE
Report the mean and the standard deviation of the mean squared errors with normalized predictors

In [177]:
results = pd.concat([results, get_mean_and_std_from_mse_list('B', mse_list_model_b)])
results

  Model         Mean     St. Dev.
0     A  1374.307390  2147.179694
0     B  1113.669025    85.452920

**The mean of model B is marginaly better with model A, but the std dev is much better. The model seems to have a lot more confidence in the mean value.**

# C. Increate the number of epochs
Repeat Part B but use 100 epochs this time for training.

In [156]:
# creating a list to hold all mean squared errors
mse_list_model_c = []

# training the model 100 times and getting the mse for each iteration, storing the values in the list
for i in range(100): # tqdm is a library to get a nice progression bar
    # creating the model
    print(f"Model C epoch {i+1} of 100")
    model_c = create_model_1()
    
    #fitting the model with the normalized data
    model_c.fit(X_norm, y_train, validation_split=0.3, epochs=50, verbose=0, batch_size=64)
    
    # using the model to predict values
    y_hat_c = model_c.predict(X_norm_test)
    
    # append mse between predicted data and actual data
    mse_list_model_c.append(mean_squared_error(y_test, y_hat_c))

Model C epoch 1 of 100
10/10 [==============================] - 0s 788us/step
Model C epoch 2 of 100
10/10 [==============================] - 0s 793us/step
Model C epoch 3 of 100
10/10 [==============================] - 0s 842us/step
Model C epoch 4 of 100
10/10 [==============================] - 0s 731us/step
Model C epoch 5 of 100
10/10 [==============================] - 0s 802us/step
Model C epoch 6 of 100
10/10 [==============================] - 0s 776us/step
Model C epoch 7 of 100
10/10 [==============================] - 0s 758us/step
Model C epoch 8 of 100
10/10 [==============================] - 0s 828us/step
Model C epoch 9 of 100
10/10 [==============================] - 0s 855us/step
Model C epoch 10 of 100
10/10 [==============================] - 0s 766us/step
Model C epoch 11 of 100
10/10 [==============================] - 0s 770us/step
Model C epoch 12 of 100
10/10 [==============================] - 0s 825us/step
Model C epoch 13 of 100
10/10 [==============================] - 0s 758us/step
Model C epoch 14 of 100
10/10 [==============================] - 0s 764us/step
Model C epoch 15 of 100
10/10 [==============================] - 0s 803us/step
Model C epoch 16 of 100
10/10 [==============================] - 0s 682us/step
Model C epoch 17 of 100
10/10 [==============================] - 0s 795us/step
Model C epoch 18 of 100
10/10 [==============================] - 0s 794us/step
Model C epoch 19 of 100
10/10 [==============================] - 0s 680us/step
Model C epoch 20 of 100
10/10 [==============================] - 0s 888us/step
Model C epoch 21 of 100
10/10 [==============================] - 0s 872us/step
Model C epoch 22 of 100
10/10 [==============================] - 0s 899us/step
Model C epoch 23 of 100
10/10 [==============================] - 0s 886us/step
Model C epoch 24 of 100
10/10 [==============================] - 0s 744us/step
Model C epoch 25 of 100
10/10 [==============================] - 0s 777us/step
Model C epoch 26 of 100
10/10 [==============================] - 0s 670us/step
Model C epoch 27 of 100
10/10 [==============================] - 0s 900us/step
Model C epoch 28 of 100
10/10 [==============================] - 0s 857us/step
Model C epoch 29 of 100
10/10 [==============================] - 0s 791us/step
Model C epoch 30 of 100
10/10 [==============================] - 0s 701us/step
Model C epoch 31 of 100
10/10 [==============================] - 0s 790us/step
Model C epoch 32 of 100
10/10 [==============================] - 0s 735us/step
Model C epoch 33 of 100
10/10 [==============================] - 0s 759us/step
Model C epoch 34 of 100
10/10 [==============================] - 0s 871us/step
Model C epoch 35 of 100
10/10 [==============================] - 0s 914us/step
Model C epoch 36 of 100
10/10 [==============================] - 0s 690us/step
Model C epoch 37 of 100
10/10 [==============================] - 0s 730us/step
Model C epoch 38 of 100
10/10 [==============================] - 0s 645us/step
Model C epoch 39 of 100
10/10 [==============================] - 0s 768us/step
Model C epoch 40 of 100
10/10 [==============================] - 0s 794us/step
Model C epoch 41 of 100
10/10 [==============================] - 0s 698us/step
Model C epoch 42 of 100
10/10 [==============================] - 0s 705us/step
Model C epoch 43 of 100
10/10 [==============================] - 0s 718us/step
Model C epoch 44 of 100
10/10 [==============================] - 0s 679us/step
Model C epoch 45 of 100
10/10 [==============================] - 0s 657us/step
Model C epoch 46 of 100
10/10 [==============================] - 0s 768us/step
Model C epoch 47 of 100
10/10 [==============================] - 0s 720us/step
Model C epoch 48 of 100
10/10 [==============================] - 0s 749us/step
Model C epoch 49 of 100
10/10 [==============================] - 0s 738us/step
Model C epoch 50 of 100
10/10 [==============================] - 0s 645us/step
Model C epoch 51 of 100
10/10 [==============================] - 0s 764us/step
Model C epoch 52 of 100
10/10 [==============================] - 0s 879us/step
Model C epoch 53 of 100
10/10 [==============================] - 0s 774us/step
Model C epoch 54 of 100
10/10 [==============================] - 0s 691us/step
Model C epoch 55 of 100
10/10 [==============================] - 0s 753us/step
Model C epoch 56 of 100
10/10 [==============================] - 0s 910us/step
Model C epoch 57 of 100
10/10 [==============================] - 0s 754us/step
Model C epoch 58 of 100
10/10 [==============================] - 0s 651us/step
Model C epoch 59 of 100
10/10 [==============================] - 0s 730us/step
Model C epoch 60 of 100
10/10 [==============================] - 0s 682us/step
Model C epoch 61 of 100
10/10 [==============================] - 0s 753us/step
Model C epoch 62 of 100
10/10 [==============================] - 0s 715us/step
Model C epoch 63 of 100
10/10 [==============================] - 0s 758us/step
Model C epoch 64 of 100
10/10 [==============================] - 0s 708us/step
Model C epoch 65 of 100
10/10 [==============================] - 0s 693us/step
Model C epoch 66 of 100
10/10 [==============================] - 0s 661us/step
Model C epoch 67 of 100
10/10 [==============================] - 0s 770us/step
Model C epoch 68 of 100
10/10 [==============================] - 0s 709us/step
Model C epoch 69 of 100
10/10 [==============================] - 0s 696us/step
Model C epoch 70 of 100
10/10 [==============================] - 0s 706us/step
Model C epoch 71 of 100
10/10 [==============================] - 0s 699us/step
Model C epoch 72 of 100
10/10 [==============================] - 0s 667us/step
Model C epoch 73 of 100
10/10 [==============================] - 0s 784us/step
Model C epoch 74 of 100
10/10 [==============================] - 0s 650us/step
Model C epoch 75 of 100
10/10 [==============================] - 0s 731us/step
Model C epoch 76 of 100
10/10 [==============================] - 0s 874us/step
Model C epoch 77 of 100
10/10 [==============================] - 0s 716us/step
Model C epoch 78 of 100
10/10 [==============================] - 0s 723us/step
Model C epoch 79 of 100
10/10 [==============================] - 0s 708us/step
Model C epoch 80 of 100
10/10 [==============================] - 0s 742us/step
Model C epoch 81 of 100
10/10 [==============================] - 0s 688us/step
Model C epoch 82 of 100
10/10 [==============================] - 0s 760us/step
Model C epoch 83 of 100
10/10 [==============================] - 0s 781us/step
Model C epoch 84 of 100
10/10 [==============================] - 0s 746us/step
Model C epoch 85 of 100
10/10 [==============================] - 0s 771us/step
Model C epoch 86 of 100
10/10 [==============================] - 0s 936us/step
Model C epoch 87 of 100
10/10 [==============================] - 0s 741us/step
Model C epoch 88 of 100
10/10 [==============================] - 0s 736us/step
Model C epoch 89 of 100
10/10 [==============================] - 0s 680us/step
Model C epoch 90 of 100
10/10 [==============================] - 0s 675us/step
Model C epoch 91 of 100
10/10 [==============================] - 0s 737us/step
Model C epoch 92 of 100
10/10 [==============================] - 0s 1ms/step
Model C epoch 93 of 100
10/10 [==============================] - 0s 790us/step
Model C epoch 94 of 100
10/10 [==============================] - 0s 743us/step
Model C epoch 95 of 100
10/10 [==============================] - 0s 658us/step
Model C epoch 96 of 100
10/10 [==============================] - 0s 720us/step
Model C epoch 97 of 100
10/10 [==============================] - 0s 766us/step
Model C epoch 98 of 100
10/10 [==============================] - 0s 758us/step
Model C epoch 99 of 100
10/10 [==============================] - 0s 726us/step
Model C epoch 100 of 100
10/10 [==============================] - 0s 758us/step

## Compute MSE
Report the mean and the standard deviation of the mean squared errors with 100 epochs

In [178]:
results = pd.concat([results, get_mean_and_std_from_mse_list('C', mse_list_model_c)])
results

  Model         Mean     St. Dev.
0     A  1374.307390  2147.179694
0     B  1113.669025    85.452920
0     C  1098.236959    89.472087

**In this case, increasing the number of epochs in model C doesn't seem to make any meaningful difference with model B**

# D. Increase the number of hidden layers
Repeat part B but use a neural network with 3 hidden layers, each of 10 nodes and ReLU activation function.

In [158]:
# creating a neural network with 3 hidden layers of 10 nodes, and a ReLU activation function
# using the adam optimizer and the mean squared error as the loss function
def create_model_2():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(X_train.shape[1],))) # input shape is the number of columns of X_train
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))

    # compiling the model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [160]:
# creating a list to hold all mean squared errors
mse_list_model_d = []

# training the model 50 times and getting the mse for each iteration, storing the values in the list
for i in range(50):
    # creating the model
    print(f"Model D epoch {i+1} of 50")
    model_d = create_model_2()
    
    #fitting the model with the normalized data
    model_d.fit(X_norm, y_train, validation_split=0.3, epochs=50, verbose=0, batch_size=64)
    
    # using the model to predict values
    y_hat_d = model_d.predict(X_norm_test)
    
    # append mse between predicted data and actual data
    mse_list_model_d.append(mean_squared_error(y_test, y_hat_d))

Model D epoch 1 of 50
10/10 [==============================] - 0s 854us/step
Model D epoch 2 of 50
10/10 [==============================] - 0s 834us/step
Model D epoch 3 of 50
10/10 [==============================] - 0s 764us/step
Model D epoch 4 of 50
10/10 [==============================] - 0s 817us/step
Model D epoch 5 of 50
10/10 [==============================] - 0s 946us/step
Model D epoch 6 of 50
10/10 [==============================] - 0s 752us/step
Model D epoch 7 of 50
10/10 [==============================] - 0s 705us/step
Model D epoch 8 of 50
10/10 [==============================] - 0s 697us/step
Model D epoch 9 of 50
10/10 [==============================] - 0s 812us/step
Model D epoch 10 of 50
10/10 [==============================] - 0s 759us/step
Model D epoch 11 of 50
10/10 [==============================] - 0s 777us/step
Model D epoch 12 of 50
10/10 [==============================] - 0s 723us/step
Model D epoch 13 of 50
10/10 [==============================] - 0s 811us/step
Model D epoch 14 of 50
10/10 [==============================] - 0s 850us/step
Model D epoch 15 of 50
10/10 [==============================] - 0s 690us/step
Model D epoch 16 of 50
10/10 [==============================] - 0s 797us/step
Model D epoch 17 of 50
10/10 [==============================] - 0s 755us/step
Model D epoch 18 of 50
10/10 [==============================] - 0s 1ms/step
Model D epoch 19 of 50
10/10 [==============================] - 0s 814us/step
Model D epoch 20 of 50
10/10 [==============================] - 0s 730us/step
Model D epoch 21 of 50
10/10 [==============================] - 0s 856us/step
Model D epoch 22 of 50
10/10 [==============================] - 0s 798us/step
Model D epoch 23 of 50
10/10 [==============================] - 0s 759us/step
Model D epoch 24 of 50
10/10 [==============================] - 0s 773us/step
Model D epoch 25 of 50
10/10 [==============================] - 0s 769us/step
Model D epoch 26 of 50
10/10 [==============================] - 0s 808us/step
Model D epoch 27 of 50
10/10 [==============================] - 0s 699us/step
Model D epoch 28 of 50
10/10 [==============================] - 0s 777us/step
Model D epoch 29 of 50
10/10 [==============================] - 0s 713us/step
Model D epoch 30 of 50
10/10 [==============================] - 0s 772us/step
Model D epoch 31 of 50
10/10 [==============================] - 0s 743us/step
Model D epoch 32 of 50
10/10 [==============================] - 0s 803us/step
Model D epoch 33 of 50
10/10 [==============================] - 0s 779us/step
Model D epoch 34 of 50
10/10 [==============================] - 0s 778us/step
Model D epoch 35 of 50
10/10 [==============================] - 0s 739us/step
Model D epoch 36 of 50
10/10 [==============================] - 0s 732us/step
Model D epoch 37 of 50
10/10 [==============================] - 0s 704us/step
Model D epoch 38 of 50
10/10 [==============================] - 0s 830us/step
Model D epoch 39 of 50
10/10 [==============================] - 0s 789us/step
Model D epoch 40 of 50
10/10 [==============================] - 0s 799us/step
Model D epoch 41 of 50
10/10 [==============================] - 0s 806us/step
Model D epoch 42 of 50
10/10 [==============================] - 0s 774us/step
Model D epoch 43 of 50
10/10 [==============================] - 0s 785us/step
Model D epoch 44 of 50
10/10 [==============================] - 0s 799us/step
Model D epoch 45 of 50
10/10 [==============================] - 0s 772us/step
Model D epoch 46 of 50
10/10 [==============================] - 0s 743us/step
Model D epoch 47 of 50
10/10 [==============================] - 0s 786us/step
Model D epoch 48 of 50
10/10 [==============================] - 0s 772us/step
Model D epoch 49 of 50
10/10 [==============================] - 0s 879us/step
Model D epoch 50 of 50
10/10 [==============================] - 0s 774us/step

In [179]:
results = pd.concat([results, get_mean_and_std_from_mse_list('D', mse_list_model_d)])
results

  Model         Mean     St. Dev.
0     A  1374.307390  2147.179694
0     B  1113.669025    85.452920
0     C  1098.236959    89.472087
0     D   185.306286    14.236582

**Model D has both a (way) smaller mean and st. dev. error, which tends to prove that more complex neural networks perform better**